from audio.runtime import compute_standard_paths

_PATHS = compute_standard_paths(__file__)
PACKAGE_ROOT = _PATHS["PACKAGE_ROOT"]
PROJECT_ROOT = _PATHS["PROJECT_ROOT"]
PACKAGE_ASSETS_ROOT = _PATHS["PACKAGE_ASSETS_ROOT"]
PROJECT_ASSETS_ROOT = _PATHS["PROJECT_ASSETS_ROOT"]
COMMON_PACKAGE_ASSETS_ROOT = _PATHS["COMMON_PACKAGE_ASSETS_ROOT"]
ASSETS_ROOT = _PATHS["ASSETS_ROOT"]
DEFAULT_BGM_DIR = (ASSETS_ROOT / "bgm").resolve()
TESTS_ROOT = _PATHS["TESTS_ROOT"]
PACKAGE_PROFILE_ROOT = _PATHS["PACKAGE_PROFILE_ROOT"]
