from __future__ import annotations

from pathlib import Path


def build_static_ffmpeg_cmd(
    *,
    ffmpeg_base: list[str],
    cover: Path,
    audio: Path,
    output: Path,
    vf_filter: str,
    video_codec: str,
    preset: str,
    crf: int,
    tune: str,
    fps: int,
    audio_codec: str,
    audio_bitrate: str,
    movflags: str,
) -> list[str]:
    return [
        *ffmpeg_base,
        "-y",
        "-loop",
        "1",
        "-i",
        str(cover),
        "-i",
        str(audio),
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-vf",
        vf_filter,
        "-c:v",
        video_codec,
        "-preset",
        preset,
        "-crf",
        str(crf),
        "-tune",
        tune,
        "-r",
        str(fps),
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        audio_codec,
        "-b:a",
        audio_bitrate,
        "-movflags",
        movflags,
        "-shortest",
        str(output),
    ]


def build_slideshow_ffmpeg_cmd(
    *,
    ffmpeg_base: list[str],
    concat_list: Path,
    audio: Path,
    output: Path,
    vf_filter: str,
    video_codec: str,
    preset: str,
    crf: int,
    tune: str,
    audio_codec: str,
    audio_bitrate: str,
    movflags: str,
) -> list[str]:
    return [
        *ffmpeg_base,
        "-y",
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(concat_list),
        "-i",
        str(audio),
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-fps_mode",
        "vfr",
        "-vf",
        vf_filter,
        "-c:v",
        video_codec,
        "-preset",
        preset,
        "-crf",
        str(crf),
        "-tune",
        tune,
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        audio_codec,
        "-b:a",
        audio_bitrate,
        "-movflags",
        movflags,
        "-shortest",
        str(output),
    ]
